### ISSUE TITLE
Handle special characters in commit messages

### ISSUE THREAD

**Issue by debben** [es-git/es-git#18]
I've run into an issue using the object-mixin. If a commit message has special characters, the encodeObject function throws an exception about the input array being too long. The issue is in `joinWithNewline`:

```
function joinWithNewline(...values : (string | Uint8Array)[]){
  const sum = values.reduce((sum, x) => sum + x.length, 0);
  const result = new Uint8Array(values.length-1 + sum);
  let offset = 0;
  for (const arr of values) {
    if(offset > 0){
      result.set([NEWLINE], offset++);
    }
    if(typeof(arr) === 'string'){
      result.set(encode(arr), offset);
    }else{
      result.set(arr, offset);
    }
    offset += arr.length;
  }
  return result;
}
```
The reduce which figures out the size of the result array assumes that the result of Uint8 encoding of strings will end up being arrays of the same length as the original string. If an input string has a special character though, the uint8 encoding could potentially be multiple bytes.

**Comment by mariusGundersen** [comment]
I've just published v0.10.0 of all the es-git packages, which includes this fix and upgrading of lots of dependencies and build stuff. A lot has happened in the world of javascript since v0.9.0 almost 2 years ago. You probably have to upgrade some dependencies and peer-dependencies (for example babel has been upgraded to v7, so you might need @babel/runtime now). 

Please let me know if this works better
